### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by ExplosiveVI** [renrizzolo/lightgallery-for-gutenberg#1]
Hi, I'm messing around with Gutenberg on a test site and I wanted to give this a go. How do I actually go about installing it onto a Wordpress site please? Could you please write a step by step idiots guide?

**Comment by renrizzolo** [comment]
Hi!
I had not looked at this for a few months and due to a bunch of changes to Gutenberg it was quite broken.
I (think) I've fixed it now - it's working on WordPress 5 for me.

### Installation:

- Download the plugin:
  - Press the green Clone or download button from the repository front page
  - Click download zip

- Install the plugin
  - unzip the downloaded zip file
  - move/ftp the whole `lightgallery-for-gutenberg-master` folder into your WordPress install's plugins folder `wp-content/plugins`

It should now show up in your wordpress backend, activate it on the plugins page.

Add the `lightgallery gallery` block to your post to use.

Let me know if you need any more information.

**Comment by ExplosiveVI** [comment]
Thanks for that Ren, I've managed to install it now. 

It is missing some of the premium features but that's to be expected as this isn't a paid version.

I did also have the similar Lightbox with PhotoSwipe installed and the gallery images were launching PhotoSwipe rather than lightgallery till I disabled it.

**Comment by renrizzolo** [comment]
@ExplosiveVI no worries.
I'm definitely not attempting to compete with any premium plugins, it was more of a personal development exercise, but if it works for you that's awesome!

I don't know that plugin but I guess they're using the same selector for launching the gallery? This uses `.lg-open`.

**Comment by ExplosiveVI** [comment]
I think it's just launching on any image that links to the media file directly. It's unlikely anyone is going to be using more than one lightbox on a single site anyway.

Thanks again for the instructions I can have a good play with it now.
